carnisj/bcdi

bcdi/graph/graph_utils.py
bcdi/preprocessing/maskMaker.py
bcdi/preprocessing/preprocessing_utils.py

merge the maskMaker class into master

Bcdi devel

---

bcdi/postprocessing/postprocessing_utils.py
bcdi/postprocessing/scripts/strain.py
bcdi/postprocessing/scripts/strain_detframe.py
bcdi/preprocessing/nxsReady.py
bcdi/preprocessing/preprocessing_utils.py
bcdi/preprocessing/scripts/concatenate_scans.py
bcdi/utils/scripts/parse_fio2spec.py

Fix syntax warning over comparison of literals using is.

---

CONTRIBUTING.md

Split the workflow in CONTRIBUTING.md for clarity

Refactor: update CONTRIBUTING.md

---

bcdi/graph/graph_utils.py

the docstring is not displayed for the __init__ method

Refactor: update class docstring so that it is displayed on ReadTheDocs

---

README.rst

Refactor: correct RST formatting

---

scripts/algorithms/bcdi_flatten_intensity.py
scripts/graph/bcdi_scan_analysis.py
scripts/graph/bcdi_scan_movie.py
scripts/graph/bcdi_view_ccf.py
scripts/graph/bcdi_view_ccf_map.py
scripts/graph/bcdi_view_mesh.py
scripts/graph/bcdi_view_psf.py
scripts/xcca/bcdi_xcca_3D_map_polar.py
scripts/xcca/bcdi_xcca_3D_rect.py

Refactor: PEP 8

---

scripts/graph/bcdi_scan_analysis.py

use literal syntax for faster code execution

Refactor: use literal syntax to create the dictionnary

---

.gitignore
CONTRIBUTING.md
bcdi/postprocessing/postprocessing_utils.py
bcdi/preprocessing/ReadNxs3.py
bcdi/utils/image_registration.py
dodo.py
environment.yml
requirements.txt
scripts/postprocessing/bcdi_post_process_BCDI_2D.py
scripts/publication/bcdi_compa_simu_exp.py
scripts/publication/bcdi_diffpattern_isosurf_3D.py
scripts/simulation/bcdi_diffraction_angles.py
scripts/utils/bcdi_primes.py
setup.py

Implement doit for tests with coverage and black

Implement doit for tests with coverage and black

---

bcdi/experiment/experiment_utils.py
bcdi/preprocessing/ReadNxs3.py
dodo.py
environment.yml
requirements.txt
setup.py

- Update the list of dependencies
- Refactor: correct code style

Add a task for code style check in dodo.py

---

HISTORY.rst
README.rst

Please include a summary of the change and which issue is fixed. Please also include 
relevant motivation and context. List any dependencies that are required for this 
change.
Fixes #67
work as expected)
Please describe the tests that you ran to verify your changes. Provide instructions 
so that the tests can be reproduced. Please also list any relevant details for your 
test configuration
**Test Configuration**:
* OS: Windows 10
* Python version: 3.8

Update  Documentation 

---

scripts/preprocessing/bcdi_rescale_support.py

SetupPostprocessing does not exist anymore

replace call to deprecated class

---

.deepsource.toml
bcdi/experiment/beamline.py
bcdi/experiment/detector.py
bcdi/experiment/diffractometer.py
bcdi/experiment/setup.py
doc/conf.py
scripts/facet_recognition/bcdi_polarplot.py
scripts/graph/bcdi_scan_analysis.py
scripts/graph/bcdi_view_mesh.py
scripts/postprocessing/bcdi_correct_angles_detector.py
scripts/postprocessing/bcdi_prtf_BCDI.py
scripts/postprocessing/bcdi_prtf_BCDI_2D.py
scripts/postprocessing/bcdi_rocking_curves.py
scripts/postprocessing/bcdi_strain.py
scripts/preprocessing/bcdi_preprocess_BCDI.py
scripts/preprocessing/bcdi_preprocess_CDI.py
scripts/preprocessing/bcdi_read_BCDI_scan.py
scripts/preprocessing/bcdi_read_data_P10.py
scripts/simulation/bcdi_domain_orientation.py
scripts/simulation/bcdi_simu_diffpattern_BCDI.py
scripts/simulation/bcdi_simu_diffpattern_CDI.py
tests/experiment/test_detector.py

Use inheritance and create child classes for each detector.
Move is_series from Detector to Setup
Add some tests

Refactor the module detector

---

.gitignore
bcdi/algorithms/algorithms_utils.py
bcdi/experiment/diffractometer.py
bcdi/experiment/setup.py
bcdi/facet_recognition/facet_utils.py
bcdi/graph/graph_utils.py
bcdi/postprocessing/postprocessing_utils.py
bcdi/preprocessing/preprocessing_utils.py
bcdi/simulation/simulation_utils.py
bcdi/utils/utilities.py
bcdi/utils/validation.py
bcdi/xcca/xcca_utils.py
scripts/graph/bcdi_visu_2D_slice.py
scripts/simulation/bcdi_domain_orientation.py
scripts/simulation/bcdi_simu_diffpattern_BCDI.py
tests/utils/test_validation.py

Remove redundant code for the validation of numpy arrays, create a generic validation function instead

Use validation function

---

HISTORY.rst
bcdi/experiment/beamline.py
bcdi/preprocessing/preprocessing_utils.py
bcdi/utils/validation.py
tests/utils/test_validation.py

+ implement more unit tests about validation functions

remove redundant code in Beamline child classes

---

bcdi/experiment/detector.py
bcdi/utils/validation.py
tests/experiment/test_detector.py

The module detector is now fully tested (0.9915)

add unit tests

---

README.rst
bcdi/experiment/rotation_matrix.py
doc/conf.py
doc/index.rst
setup.py

add some class diagrams using mermaid

update the documentation

---

bcdiHackweek/docs/index.md
bcdiHackweek/mkdocs.yml

Docs for the bcdiHackweek
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions 
so that the tests can be reproduced.
**Test Configuration**: conda
* OS: windows
* Python version: 3.8.11

Bcdi hackweek

---

bcdi/experiment/diffractometer.py
bcdi/utils/utilities.py
tests/utils/test_utilities.py

Check is only done with float, hence the renaming
[X] Refactoring

Refactor: rename utilities.is_numeric to is_float

---

bcdi/experiment/rotation_matrix.py

Describe the reference frame
Use explicit name for variable

Update docstring of RotationMatrix

---

README.rst

Gather published article/dataset in a paragraph in README

---

README.rst
doc/HISTORY.rst
dodo.py

- replace a broken link as well

Add task in *doit* to check broken links in the doc

---

bcdi/graph/graph_utils.py
bcdi/postprocessing/facet_recognition.py
bcdi/utils/validation.py
environment.yml
requirements.txt
tests/facet_recognition/test_facet_utils.py
tests/postprocessing/test_facet_analysis.py

Deepsource

---

bcdi/preprocessing/ReadNxs3.py
bcdi/preprocessing/bcdi_utils.py
scripts/preprocessing/bcdi_preprocess_BCDI.py
setup.py

Summary of the change and which issue it fixes.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions 
so that the tests can be reproduced.
**Test Configuration**:
* OS:
* Python version:
* ...

Correct angles

---

bcdi/graph/graph_utils.py
bcdi/postprocessing/facet_analysis.py
bcdi/postprocessing/postprocessing_runner.py
bcdi/preprocessing/preprocessing_runner.py
bcdi/utils/io_helper.py
doc/HISTORY.rst
scripts/postprocessing/bcdi_strain.py

I reset the tree since simply replacing plt by fig works. I can't believe I did not try that before, pretty sure I had tried :'(
Fixes #144  (issue)
Debian 11 testing, python 3.9

Fix figure saving issue

---

bcdi/utils/parameters.py
bcdi/utils/parser.py
doc/HISTORY.rst
doc/modules/utils/index.rst
environment.yml
requirements.txt
setup.py

Release the constraint on scikit-image version, which is not needed anymore.
Add newly written modules to the documentation.

Release constraint on skimage version

---

bcdi/experiment/diffractometer.py

Add a description of `sample_offsets` in the documentation of the diffractometer module
Fixes #159

Add a description of `sample_offsets` in the documentation

---

bcdi/examples/S11_config_postprocessing.yml
bcdi/examples/S11_config_preprocessing.yml
bcdi/postprocessing/postprocessing_runner.py
bcdi/preprocessing/preprocessing_runner.py
bcdi/utils/parameters.py
scripts/postprocessing/bcdi_strain.py
scripts/preprocessing/bcdi_preprocess_BCDI.py

Basically everything is already there for a silent operation: backend 'agg' which saves the figures without showing them, parameter 'reconstruction_file' in the config which avoids opening a pop-up window to choose the phased file in postprocessing, parameter `flag_interact` to avoid the interactive masking in preprocessing.
I simply cleaned up a bit the logic and docstrings to make things more obvious.
Fixes #247 
Example dataset

Silent mode

---

bcdi/graph/graph_utils.py

Trying to catch the error to prevent the bog on the linecut.
This needs some testing first

Catch IndexError if fits on linecuts are not successful

---

bcdi/__init__.py
doc/HISTORY.rst
doc/index.rst
tests/graph/test_linecut.py

Release 0.2.8

---

bcdi/postprocessing/process_scan.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/process_scan.py
doc/HISTORY.rst
requirements.txt
setup.py
tests/preprocessing/test_bcdi_utils.py

Previously the functionalities regarding Bragg peak finding, rocking curve fitting and plotting were located in tightly binded functions. This was difficult to maintain and also introduced some unnecessary temporal coupling. A class PeakFinder is implemented to gather these functionalities and manage its own state properly.

Implement PeakFinder for the calculation of corrected detector angles

---

bcdi/postprocessing/postprocessing_runner.py
bcdi/postprocessing/raw_orthogonalization.py
doc/HISTORY.rst
scripts/postprocessing/bcdi_orthogonalization.py

A new post-processing script for the orthogonalization only.
Fixes # (issue)
It fixes the issue #316 
I ran the code on my machine.
**Test Configuration**:
* OS: Ubuntu 20
* Python version: 3.9

Interpolation script

---

bcdi/postprocessing/analysis.py
bcdi/postprocessing/process_scan.py
bcdi/postprocessing/raw_orthogonalization.py
tests/postprocessing/test_analysis.py

Update the dictionary of parameters inside the method `analysis.update_detector_angles`, as this step is coupled with updating the detector angles.

Remove some temporal coupling in `analysis.update_detector_angles`

---

bcdi/__init__.py
doc/HISTORY.rst

prepare for version 0.2.9

---

bcdi/__init__.py
doc/HISTORY.rst
doc/index.rst

prepare for version 0.3.1

---

.gitignore
doc/conf.py
dodo.py

Add some modules to autodoc_mock_imports in conf.py
Increase verbose in dodo.py for the task build_doc

solve issues with building the doc

---

doc/requirements.txt
readthedocs.yml
requirements.txt
setup.py

Update the config following latest recommendation from ReadTheDocs, see https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

Update Readthedocs configuration file
