bcdi/experiment/experiment_utils.py
tests/experiment/test_diffractometer.py
tests/utils/test_utilities.py

Use the abc module instead of throwing exceptions if the child class does not override the method

Refactor: use @abstractmethod in Diffractometer

---

HISTORY.rst
scripts/postprocessing/bcdi_prtf_BCDI.py
scripts/postprocessing/bcdi_prtf_BCDI_2D.py

If the user do not provide a mask (by closing the pop-up window), an empty mask is automatically generated.
* OS: Windows
* Python version: 3.8.8
- [X ] I have reviewed my code and checked for misspellings

Allow the user to not provide a mask in the prtf calculation

---

bcdi/experiment/beamline.py
bcdi/experiment/diffractometer.py
bcdi/experiment/setup.py
bcdi/preprocessing/preprocessing_utils.py
doc/modules/experiment/index.rst
scripts/preprocessing/bcdi_preprocess_BCDI.py
tests/experiment/test_beamline.py

Instead of a single dictionary of parameters, use the explicit signature.
Remove all references to xrayutilities frame, use only the laboratory frame.
Use lookup dictionaries instead of hardcoding values in methods.
Update the doc

us explicit signature for methods 

---

doc/modules/experiment/index.rst
environment.yml
requirements.txt

autoclasstree cannot resolve submodules on ReadTheDocs (although the doc builds correctly locally)

define class diagrams in mermaid instead of using autoclasstree

---

bcdi/experiment/beamline.py
bcdi/experiment/diffractometer.py
bcdi/experiment/setup.py
bcdi/preprocessing/bcdi_utils.py
scripts/facet_recognition/bcdi_polarplot.py
scripts/postprocessing/bcdi_prtf_BCDI.py
scripts/postprocessing/bcdi_prtf_BCDI_2D.py
scripts/preprocessing/bcdi_preprocess_BCDI.py

Motors for ID01 are now loaded as if they were scanned, and default to positioners otherwise.
The parameter "follow_bragg" is not needed anymore, I removed it from the scripts and API.
For the monitor, now you can provide it in the "actuators" parameter if it is different from "exp1", e.g. actuators ={"monitor": "mon2"}
[X] I have run doit
t

allow gridding d2scan in preprocessing

---

scripts/postprocessing/bcdi_strain.py
scripts/preprocessing/bcdi_preprocess_BCDI.py

The key corresponding to the config file in the dictionary of command line parameters was wrong.

Bug: use the correct key for the config file

---

scripts/postprocessing/bcdi_strain.py

if data_dir is not specified, it will open by default in detector.scandir as previously (parent folder of the data directory)

open the pop-up window in data_dir if specified

---

bcdi/experiment/detector.py
bcdi/postprocessing/facet_analysis.py
bcdi/utils/parameters.py
conf/config_preprocessing.yml
doc/HISTORY.rst
scripts/postprocessing/bcdi_strain.py
scripts/preprocessing/bcdi_preprocess_BCDI.py
tests/experiment/test_detector.py

In order to keep it compatible with the use of config files, instead of defining a function now the user must specify the coefficients of a 4th order polynomial (or None if unused).
Fixes #191 
- preprocessing of ID01 dataset with/without linearity_function runs as expected
- unit tests modified accordingly

Update the parameter "Linearity_function"

---

bcdi/experiment/diffractometer.py
bcdi/utils/utilities.py
conf/config_preprocessing.yml
doc/HISTORY.rst
doc/modules/experiment/index.rst
scripts/postprocessing/bcdi_correct_angles_detector.py
scripts/preprocessing/bcdi_preprocess_BCDI.py

Add support in preprocessing for 34ID (loading TIFF images)
Fixes #192 
preprocessing_BCDI.py and correct_angles_detector.py runs as expected for a 34ID dataset

add support in preprocessing for 34ID-C

---

bcdi/experiment/setup.py
bcdi/preprocessing/bcdi_utils.py
doc/HISTORY.rst
scripts/postprocessing/bcdi_strain.py
scripts/preprocessing/bcdi_preprocess_BCDI.py

The methods setup.ortho_directspace and setup.ortho_reciprocal now return also the transformation matrix from the detector frame to the laboratory frame. The matrix can then be saved as other parameters
Fixes #185 
- 
pre- and postprocessing scripts run as expected.

return the transformation matrix from the detector frame to the laboratory frame

---

bcdi/experiment/beamline.py
bcdi/experiment/detector.py
bcdi/experiment/diffractometer.py
bcdi/experiment/setup.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/cdi_utils.py
bcdi/utils/parameters.py
bcdi/utils/utilities.py
conf/config_postprocessing.yml
doc/HISTORY.rst
scripts/graph/bcdi_scan_analysis.py
scripts/graph/bcdi_view_mesh.py
scripts/postprocessing/bcdi_correct_angles_detector.py
scripts/postprocessing/bcdi_polarplot.py
scripts/postprocessing/bcdi_rocking_curves.py
scripts/postprocessing/bcdi_strain.py
scripts/preprocessing/bcdi_preprocess_BCDI.py
scripts/preprocessing/bcdi_preprocess_CDI.py
scripts/preprocessing/bcdi_read_BCDI_scan.py
tests/experiment/test_beamline.py
tests/experiment/test_diffractometer.py
tests/experiment/test_setup.py
tests/utils/test_utilities.py

When some parameters such as the detector angles, energy, sample to detector distance and tilt_angle are not provided in the config file, the code selects values from the logfile or raises an error if not available. The detector distance is available only for 34ID-C (as a motor) and ID01 (after some parsing).
The parameter "template_imagefile" is now optional for P10 postprocessing.
The redundant parameter "logfile" has been removed from calls to instance methods, because it can be accessed directly as a property of the setup intance. 
Fixes #189 and #190 
Preprocessing on ID10 data and postprocessing on 34ID-C data works as expected.

Load positions from the log file when available (Lazy user)

---

bcdi/experiment/beamline.py
doc/HISTORY.rst

The number of values to unpack from the call to beamline.Beamline.process_position was not correct (detector distance was not taken into account). The code for all beamlines has been corrected.
Fixes #220 
- 
**Test Configuration**:
Tested on ID01 dataset with interpolation using xrayutilities.

use the correct number of values to unpack (detector distance missing)

---

doc/conf.py

add numpy, ipywidgets and pandas to autodoc_mock_imports in order to solve an improper building of the documentation on ReadTheDocs

add numpy, ipywidgets and pandas to autodoc_mock_imports

---

MANIFEST.in
bcdi/__init__.py
bcdi/experiment/setup.py
bcdi/postprocessing/facet_analysis.py
doc/EXAMPLE_POSTPROCESSING.rst
doc/HISTORY.rst

Use the binned detector pixel size to calculate the transformation matrices.
One needs to use detector.pixelsize_x (_y) instead of the unbinned pixel size. This bug was introduced when moving the properties pixelsize_x (_y) from the Setup class to the Detector class.
I added another modes.h5 with preprocessing=[1,2,2].
I will use it later to implement a high-level test about the interpolation (e.g. using the number of support voxels in the interpolated result)
Fixes #219 
Interpolation of the example dataset in an orthonormal frame works correctly now with preprocessing_binning = (1,2,2).

Bug: apply correctly binning to the pixel size used in the transformation matrices

---

bcdi/utils/parameters.py
bcdi/utils/parser.py
doc/HISTORY.rst
tests/utils/test_parameters.py
tests/utils/test_parser.py

Now the command line parameters do not need to be provided. ConfigParser can be instantiated providing only the path to the config file
Fixes #230 
The error with the weird string value of `flip_reconstruction` in the GUI is solved.

Set command line parameters as optional

---

bcdi/__init__.py
bcdi/experiment/beamline.py
bcdi/experiment/loader.py
bcdi/experiment/setup.py
bcdi/preprocessing/ReadNxs3.py
bcdi/preprocessing/nxsReady.py
bcdi/utils/io_helper.py
bcdi/utils/utilities.py
doc/HISTORY.rst
tests/algorithms/test_algorithms_utils.py
tests/config.py
tests/experiment/test_beamline.py
tests/experiment/test_detector.py
tests/experiment/test_diffractometer.py
tests/experiment/test_loader.py
tests/experiment/test_rotation_matrix.py
tests/experiment/test_setup.py
tests/facet_recognition/test_facet_utils.py
tests/graph/test_graph_utils.py
tests/postprocessing/test_facet_analysis.py
tests/postprocessing/test_postprocessing_utils.py
tests/preprocessing/test_bcdi_utils.py
tests/simulation/test_supportMaker.py
tests/utils/test_image_registration.py
tests/utils/test_io_helper.py
tests/utils/test_parameters.py
tests/utils/test_parser.py
tests/utils/test_utilities.py
tests/utils/test_validation.py

Fixes #234 
A class ContextFile implementing the context manager protocol was created. The method `loader.create_logfile` returns an instance of ContextFile, allowing its safe usage in other methods via the decorators `@safeload` and `@safeload_static`.
The signature of `loader.create_logfile` has been refactored, so that all overriding methods share the same signature with the overriden base class abstract method.
A new function `utilities.unpack_array` has been implemented, to avoid hard-coding array slices in methods using motor positions.
Refactor: open files within context managers in `utilities.load_file`.
[X] Breaking change
[X] I implemented unit-tests
[X] Tests pass
[X] I updated the documentation
The modifications have been tested on experimental datasets from ID01, ID01BLISS, …

Open files within context managers

---

.github/workflows/python-package-3.8.yml
.github/workflows/python-package-3.9.yml

bcdi is now installed before running the tests, so that we get an error if something is wrong in setup.py
I also updated the workflows and removed hard-coded paths

test installing bcdi in CI

---

bcdi/examples/S11_config_preprocessing.yml
bcdi/graph/graph_utils.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/preprocessing_runner.py
bcdi/preprocessing/process_scan.py
bcdi/utils/parameters.py
bcdi/utils/utilities.py
doc/HISTORY.rst
scripts/preprocessing/bcdi_preprocess_BCDI.py

Add the option to preprocess multiple scans using multiprocessing. In this case, `flag_interact` has to be False, and an optional mask can be loaded to be applied on the data. The use case is when one runs once the preprocessing manually and creates such a mask (it is saved automatically after the interactive masking as `interactive_mask.npz`), and afterwards wants to apply it to a series of scans measured in the same geometry.
The parameter `mask` was therefore added to the config files. The loaded mask will be used independently of `flag_interact`.
- 
Test with two scans, with and without mask.

Implement multiprocessing for the preprocessing

---

bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/process_scan.py

There was a pb with how the argument was loaded. It is a string and not a boolean, so the monitor would always be used.

Was using monitor even if "skip"

---

bcdi/experiment/loader.py
doc/HISTORY.rst

loader: allow loading of Eiger2M detector data at ID01BLISS

---

bcdi/experiment/beamline.py
doc/HISTORY.rst

One needs to return twice beta in BeamlineSIXS.process_positions because beta is also below the detector circles, as correctly
defined in xrayutilities Qconv object.
Fixes #267 
Test with a dataset from SIXS, the script runs correctly.

Bug: provide the correct number of motor positions to xrayutilities Qconv for SIXS

---

bcdi/examples/S11_config_postprocessing.yml
bcdi/postprocessing/postprocessing_runner.py
bcdi/postprocessing/postprocessing_utils.py
bcdi/postprocessing/process_scan.py
bcdi/utils/parameters.py
doc/HISTORY.rst
scripts/postprocessing/bcdi_strain.py

Add a parameter `skip_unwrap` to the config files, so that the user can skip phase unwrapping. This can be useful when there are defects in the crystal and phase unwrapping does not work well.
I ran the example dataset without phase unwrapping, results as expected.

FEAT: Add option to skip unwrapping

---

bcdi/__init__.py

I added the version function that may work to get the commit hash saved in the version.
It works for me on my personal laptop but not on slurm ...
You should try it 
I don't know how to want to use it, maybe : 
```python
version = "0.2.7"
def get_git_version():
"""
Get the full version name with git hash, e.g. "2020.1-65-g958b7254-dirty"
Only works if the current directory is part of the git repository.
:return: the version name
"""
from subprocess import Popen, PIPE
try:
p = Popen(['git', 'describe', '--tags', '--dirty', '--always'],
stdout=PIPE, stderr=PIPE)
return p.stdout.readlines()[0].strip().decode("UTF-8")
except:
__git_version_static__ = "git_version_placeholder"
if "placeholder" in __git_version_static__:
return version
return __git_version_static__
__version__ = …
```

Add version function

---

bcdi/postprocessing/process_scan.py
doc/HISTORY.rst
tests/postprocessing/test_postprocessing_runner.py

The correction of detector angles has been moved before the calculation of q_bragg, so that the latter uses the corrected values.
Fixes #282 
- [X ] I have run ``doit`` and all tasks have passed

Move the correction of detector angles before the calculation of q_bragg

---

bcdi/experiment/detector.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/process_scan.py
doc/HISTORY.rst

The first axis was considered as binned in `bcdi_utils.find_bragg`, but the data was not always binned accordingly beforehand, depending on the preprocessing pipeline. This is fixed by introducing a property tracking the current binning factor, which is provided as input to `find_bragg` instead of the user-defined binning.
Fixes #285

Bug: fix binning value of first axis in `find_bragg`

---

bcdi/experiment/detector.py
bcdi/utils/parameters.py
doc/HISTORY.rst
tests/postprocessing/test_postprocessing_runner.py
tests/preprocessing/test_preprocessing_runner.py
tests/utils/test_parameters.py

In scripts, the logfile was created in `save_dir` if defined, but there was not check if the folder actually existed. Now it is created in ConfigChecker.

Bug: create `save_dir` before running scripts

---

bcdi/examples/S11_config_preprocessing.yml
bcdi/utils/parameters.py
doc/HISTORY.rst
scripts/preprocessing/bcdi_preprocess.py
tests/utils/test_parameters.py

When the Bragg peak position is provided, the setting of `centering_method` is now overriden in the ConfigChecker instance.
Fixes # 288

Bug: override  `centering_method` when the Bragg peak position is provided

---

bcdi/experiment/detector.py
bcdi/experiment/loader.py
bcdi/utils/parameters.py
doc/HISTORY.rst
tests/experiment/test_detector.py

Allow `sample_name` to be an empty string, in order to match the data internal path in ID01BLISS h5 files.
E.g., the positioners could be located at "X.1/instrument/positioners", X being the scan number. In that case, there is no sample name in front of the scan number.

Allow `sample_name` to be an empty string.

---

bcdi/postprocessing/process_scan.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/process_scan.py
doc/HISTORY.rst

In the presence of hotpixels, some centering methods are not performing well (typically, those based on the center of mass). A plot of the peak position determined by each of the methods 'max', 'com' and 'max_com' is now saved automatically to help checking the validity of the parameter setting for `centering_method`.
Fix #288

Add plot to check qualitatively the centering method

---

bcdi/experiment/loader.py
bcdi/experiment/setup.py
bcdi/postprocessing/postprocessing_utils.py
bcdi/postprocessing/process_scan.py
bcdi/preprocessing/bcdi_utils.py
doc/HISTORY.rst
scripts/graph/bcdi_scan_analysis.py
scripts/graph/bcdi_view_mesh.py
scripts/postprocessing/bcdi_correct_angles_detector.py
scripts/postprocessing/bcdi_polarplot.py
scripts/postprocessing/bcdi_prtf_BCDI.py
scripts/postprocessing/bcdi_prtf_BCDI_2D.py
scripts/postprocessing/bcdi_rocking_curves.py
scripts/preprocessing/bcdi_read_BCDI_scan.py
tests/postprocessing/test_postprocessing_utils.py

Add unit tests to `postprocessing_utils.find_datarange` and make it dimension-agnostic.
Fix a bug with data path formatting in ID01BLISS loader (missing parentheses).
Do not return the logfile anymore in `setup.create_logfile` (as it should be in a setter).

Refactor postprocessing_utils.find_datarange

---

bcdi/examples/S11_config_preprocessing.yml
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/preprocessing_runner.py
bcdi/preprocessing/process_scan.py
bcdi/utils/parameters.py
doc/HISTORY.rst
scripts/preprocessing/bcdi_preprocess.py
tests/utils/test_parameters.py

The functionality provided by the parameter 'fix_size' can be obtained using the more recent set of parameters `roi_detector`, `center_roi_x` and `center_roi_y`. It is decided to remote it.
Fixes #296

remove deprecated `fix_size` parameter

---

bcdi/postprocessing/postprocessing_utils.py

typo caused error in the BCDI_strain.py script
The script now runs

fix typo error in logger usage

---

bcdi/postprocessing/analysis.py

The phase is saved in the h5 and pz files with the field name "phase", but it is called "disp" in the vti file.
Here, I just changed the name of the field name to get "phase" as a field name.

change the name of the field name for the phase in the .vti output

---

bcdi/postprocessing/analysis.py
bcdi/postprocessing/process_scan.py

#306 introduced a reproducibility issue by replacing the centering method (center of mass) in postprocessing after interpolation with the value of the parameter 'centering_method'. This is fixed by this pull request.

Bug: force centering by center of mass after interpolation

---

bcdi/experiment/detector.py
bcdi/experiment/loader.py
bcdi/experiment/setup.py
bcdi/graph/graph_utils.py
bcdi/postprocessing/analysis.py
bcdi/postprocessing/postprocessing_utils.py
bcdi/preprocessing/analysis.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/process_scan.py
bcdi/utils/utilities.py
bcdi/utils/validation.py
doc/HISTORY.rst
tests/preprocessing/test_analysis.py

Create classes Analysis, PreprocessingLoader and InteractiveMasker for preprocessing. Each preprocessing case (loading/reloading, interpolation or not) is using a child class. Refactor `preprocessing.process_scan` to use these classes, so that it is much easier to follow analysis steps.
Fixes #301

Add more OOP in preproccessing

---

bcdi/experiment/beamline.py
bcdi/experiment/beamline_factory.py
bcdi/experiment/detector.py
bcdi/experiment/diffractometer.py
bcdi/experiment/loader.py
bcdi/experiment/setup.py
bcdi/graph/colormap.py
bcdi/postprocessing/postprocessing_runner.py
bcdi/postprocessing/postprocessing_utils.py
bcdi/postprocessing/process_scan.py
bcdi/preprocessing/analysis.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/process_scan.py
bcdi/preprocessing/process_scan_cdi.py
bcdi/utils/utilities.py
doc/HISTORY.rst
doc/index.rst
tests/config.py
tests/experiment/test_detector.py
tests/experiment/test_loader.py
tests/experiment/test_setup.py
tests/postprocessing/test_analysis.py
tests/preprocessing/test_analysis.py
tests/utils/test_utilities.py

Remove temporal coupling in the initialization of the Setup instance. Set the paths, create the logfile and read it directly in `setup.__init__`. Fixes #313 

Remove temporal coupling in Setup initialization

---

bcdi/experiment/setup.py
bcdi/postprocessing/analysis.py
doc/HISTORY.rst

Previously, the interpolation of the reconstructed crystal was done directly into the crystal frame. There are some use-cases where one would like to interpolate into the laboratory frame. This required previously two interpolations (detector_frame -> crystal frame -> back to laboratory frame).
Split `setup.ortho_directspace` into methods to get the transformation matrix in the laboratory frame or crystal frame. Implement `setup.ortho_directspace_labframe` if one wants to interpolate into the laboratory frame.
Fixes #317

Implement a method to interpolate into the laboratory frame

---

bcdi/experiment/beamline_factory.py
bcdi/experiment/setup.py
bcdi/postprocessing/analysis.py
bcdi/postprocessing/postprocessing_utils.py
bcdi/postprocessing/process_scan.py
bcdi/postprocessing/raw_orthogonalization.py
bcdi/utils/parameters.py
bcdi/utils/utilities.py
doc/HISTORY.rst
doc/conf.py
tests/experiment/test_setup.py
tests/postprocessing/test_analysis.py

Fix the type conversion of the input parameter `tilt_angle` in `setup.check_setup`. When it was a float or a 0D array, the calculation of the mean would fail. 
Implement the calculation of q_bragg from the q-values saved after the interpolation by xrayutilities in preprocessing.

fix postprocessing for energy scans

---

bcdi/experiment/detector.py
bcdi/postprocessing/analysis.py
bcdi/preprocessing/analysis.py
bcdi/preprocessing/bcdi_utils.py
bcdi/preprocessing/center_fft.py
bcdi/utils/parameters.py
bcdi/utils/validation.py
doc/HISTORY.rst
tests/preprocessing/test_bcdi_utils.py
tests/preprocessing/test_center_fft.py

A parameter name in the signature of `bcdi_utils.find_bragg` was change from "roi" to "region_of_interest", therefore the region of interest was not taken into account anymore when calculating the peak position. Kwargs were allowed without check, so this problem was not creating an error.
- renamed the parameter to the expected "roi"
- added a validation check of kwargs
- added some unit tests

[Bug} Take into account the region of interest in `bcdi_utils.find_bragg`

---

bcdi/examples/S11_config_preprocessing.yml
bcdi/experiment/beamline_factory.py
bcdi/experiment/detector.py
bcdi/experiment/diffractometer.py
bcdi/experiment/loader.py
bcdi/experiment/rotation_matrix.py
bcdi/experiment/setup.py
bcdi/graph/colormap.py
bcdi/postprocessing/facet_analysis.py
bcdi/preprocessing/analysis.py
bcdi/preprocessing/bcdi_utils.py
bcdi/utils/format.py
bcdi/utils/io_helper.py
bcdi/utils/parameters.py
bcdi/utils/parser.py
bcdi/utils/utilities.py
doc/HISTORY.rst
doc/modules/postprocessing/index.rst
doc/modules/preprocessing/index.rst
doc/modules/utils/index.rst
scripts/postprocessing/bcdi_angular_profile.py
scripts/postprocessing/bcdi_line_profile.py
scripts/preprocessing/bcdi_preprocess.py
tests/utils/test_format.py
tests/utils/test_parameters.py
tests/utils/test_utilities.py

Allow the config parameter 'frames_pattern' to be a list containing only the indices of the detector frames to skip. Previously a list of the length of the data had to be provided (this is still supported though).
Fixes #330

Allow 'frames pattern' to list only the indices of the frames to exclude
